services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.kalik8s.ru,192.168.1.10:3000
      TZ: Asia/Tbilisi
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
