http_port 3128
acl agents src 172.30.0.0/24
acl to_private dst 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 127.0.0.0/8 169.254.0.0/16 100.64.0.0/10 0.0.0.0/8
acl to_private dst ::1 fc00::/7 fe80::/10
acl SSL_ports port 443
acl Safe_ports port 80 443
acl CONNECT method CONNECT
http_access deny to_private
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow agents
http_access deny all
dns_nameservers 1.1.1.1 9.9.9.9
cache deny all
access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log
pid_filename none
shutdown_lifetime 1 seconds
